package boundary;

import control.LoginController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;

public class LoginForm {

    private JPanel contentPane;
    private JTextField textEmail;
    private JPasswordField passwordField;
    private JButton accediButton;
    private JLabel PasswordLabel;
    private JPanel mainPanel;
    private JLabel passwordDimenticataLabel;
    private JLabel logoLabel;
    private JLabel titoloLabel;
    private JLabel emailLabel;

    public LoginForm() {
        URL imgURL = getClass().getResource("/logo.png");
        if (imgURL != null) {
            ImageIcon originalIcon = new ImageIcon(imgURL);
            Image scaledImage = originalIcon.getImage().getScaledInstance(250, -1, Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(scaledImage);
            logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
            logoLabel.setText("");
            logoLabel.setIcon(resizedIcon);
        } else {
            System.err.println("Errore: Impossibile trovare il file del logo.");
        }

        accediButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                login();
            }
        });
    }

    private void login() {
        String email = textEmail.getText();
        String password = new String(passwordField.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Compilare tutti i campi", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.length() >= 1000 || password.length() >= 1000) {
            JOptionPane.showMessageDialog(null, "Email e password non possono superare i 1000 caratteri", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(null, "Email non valida: deve contenere @", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }
        LoginController controller = new LoginController();
        String tipoUtente = controller.login(email.trim(), password);

        if (tipoUtente == null) {
            JOptionPane.showMessageDialog(null, "Email o password non valide", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }

        switch (tipoUtente) {
            case "MEDICO":
                Map<String,String> dati = controller.ottieniAnagraficaMedico(email.trim());
                String idMedico = dati.getOrDefault ("id", "0");
                Long id = Long.parseLong(idMedico);
                MedicoForm medicoForm =  new MedicoForm(id);
                medicoForm.apriForm();
                break;

            case "PAZIENTE":
                Map<String, String> anagraficaPaziente = controller.ottieniAnagraficaPaziente(email.trim());
                String idPaziente = anagraficaPaziente.getOrDefault("id", "0");
                Long idP= Long.parseLong(idPaziente);
                PazienteForm pazienteForm = new PazienteForm(idP);
                pazienteForm.apriForm();
                break;

            default:
                JOptionPane.showMessageDialog(null, "Ruolo utente non riconosciuto", "Errore", JOptionPane.ERROR_MESSAGE);
                return;
        }

        SwingUtilities.getWindowAncestor(contentPane).dispose();
    }

    public JFrame apriLoginForm() {
        JFrame frame = new JFrame("Ambulatorio Salus");
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBackground(new Color(-14793370));
        mainPanel.setForeground(new Color(-14793370));
        mainPanel.setMaximumSize(new Dimension(1000, 800));
        mainPanel.setMinimumSize(new Dimension(700, 500));
        mainPanel.setPreferredSize(new Dimension(800, 600));
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setBackground(new Color(-1));
        contentPane.setForeground(new Color(-1));
        contentPane.setMaximumSize(new Dimension(700, 500));
        contentPane.setMinimumSize(new Dimension(700, 500));
        contentPane.setPreferredSize(new Dimension(600, 400));
        contentPane.setRequestFocusEnabled(false);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(150, 50, 150, 50);
        mainPanel.add(contentPane, gbc);
        contentPane.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        passwordField = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 90, 0, 90);
        contentPane.add(passwordField, gbc);
        accediButton = new JButton();
        accediButton.setBackground(new Color(-10828087));
        accediButton.setForeground(new Color(-1));
        accediButton.setText("\uD83D\uDD10 ACCEDI");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(0, 130, 0, 150);
        contentPane.add(accediButton, gbc);
        passwordDimenticataLabel = new JLabel();
        passwordDimenticataLabel.setForeground(new Color(-14793370));
        passwordDimenticataLabel.setText("<html><u>Password dimenticata?</u></html>");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(0, 40, 0, 60);
        contentPane.add(passwordDimenticataLabel, gbc);
        logoLabel = new JLabel();
        logoLabel.setAlignmentX(1.0f);
        Font logoLabelFont = this.$$$getFont$$$("Arial", Font.BOLD, 24, logoLabel.getFont());
        if (logoLabelFont != null) logoLabel.setFont(logoLabelFont);
        logoLabel.setForeground(new Color(-14793370));
        logoLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(50, 100, 0, 160);
        contentPane.add(logoLabel, gbc);
        textEmail = new JTextField();
        textEmail.setAlignmentX(0.5f);
        textEmail.setAlignmentY(0.5f);
        textEmail.setAutoscrolls(false);
        textEmail.setMargin(new Insets(2, 9, 2, 6));
        textEmail.setText("");
        textEmail.setToolTipText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 90, 0, 90);
        contentPane.add(textEmail, gbc);
        PasswordLabel = new JLabel();
        Font PasswordLabelFont = this.$$$getFont$$$("Arial", -1, 16, PasswordLabel.getFont());
        if (PasswordLabelFont != null) PasswordLabel.setFont(PasswordLabelFont);
        PasswordLabel.setForeground(new Color(-14793370));
        PasswordLabel.setText("Password:");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 90, 0, 0);
        contentPane.add(PasswordLabel, gbc);
        emailLabel = new JLabel();
        Font emailLabelFont = this.$$$getFont$$$("Arial", -1, 16, emailLabel.getFont());
        if (emailLabelFont != null) emailLabel.setFont(emailLabelFont);
        emailLabel.setForeground(new Color(-14793370));
        emailLabel.setText("Email:");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(30, 90, 0, 0);
        contentPane.add(emailLabel, gbc);
        titoloLabel = new JLabel();
        Font titoloLabelFont = this.$$$getFont$$$("Arial", Font.BOLD, 16, titoloLabel.getFont());
        if (titoloLabelFont != null) titoloLabel.setFont(titoloLabelFont);
        titoloLabel.setForeground(new Color(-10828087));
        titoloLabel.setRequestFocusEnabled(false);
        titoloLabel.setText("Effettua il login al tuo account");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.insets = new Insets(50, 90, 0, 130);
        contentPane.add(titoloLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}