package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import entity.Medico;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class MedicoForm {
    private JButton logoutButton;
    private JButton leMieVisiteButton;

    public JPanel getContentPane() {
        return contentPane;
    }

    private JPanel contentPane;
    private JLabel logoLabel;
    private JTextPane textPane1;
    private JLabel titoloLabel;
    private JLabel disegnoLabel;
    private JLabel testoLabel;
    private Long idMedico;
    private String nome;
    private String cognome;
    private String email;
    private String recapito;
    private JFrame currentFrame;

    public MedicoForm(Long idMedico,
                      String nome,
                      String cognome,
                      String email,
                      String recapito) {

        this.idMedico = idMedico;
        this.nome = nome;
        this.cognome = cognome;
        this.email = email;
        this.recapito = recapito;

        logoutButton.addActionListener(e -> {

            currentFrame.dispose();

            new LoginForm().apriLoginForm();

        });

        leMieVisiteButton.addActionListener(e -> {
            new VisitaMedicoForm(idMedico, currentFrame).apriForm();

        });
    }

    public JFrame apriForm() {
        JFrame frame = new JFrame("Area Medico");
        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        this.currentFrame = frame;
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-14793370));
        Font panel1Font = this.$$$getFont$$$("Arial", Font.BOLD, 24, panel1.getFont());
        if (panel1Font != null) panel1.setFont(panel1Font);
        panel1.setForeground(new Color(-14793370));
        panel1.setPreferredSize(new Dimension(800, 600));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        leMieVisiteButton = new JButton();
        leMieVisiteButton.setBackground(new Color(-10828087));
        Font leMieVisiteButtonFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, leMieVisiteButton.getFont());
        if (leMieVisiteButtonFont != null) leMieVisiteButton.setFont(leMieVisiteButtonFont);
        leMieVisiteButton.setForeground(new Color(-1));
        leMieVisiteButton.setText("Le mie visite");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(leMieVisiteButton, gbc);
        logoutButton = new JButton();
        logoutButton.setBackground(new Color(-10828087));
        Font logoutButtonFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, logoutButton.getFont());
        if (logoutButtonFont != null) logoutButton.setFont(logoutButtonFont);
        logoutButton.setForeground(new Color(-1));
        logoutButton.setText("Logout");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(logoutButton, gbc);
        logoLabel = new JLabel();
        Font logoLabelFont = this.$$$getFont$$$("Arial", Font.BOLD, 24, logoLabel.getFont());
        if (logoLabelFont != null) logoLabel.setFont(logoLabelFont);
        logoLabel.setForeground(new Color(-16764058));
        logoLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 45, 35, 0);
        panel1.add(logoLabel, gbc);
        textPane1 = new JTextPane();
        textPane1.setBackground(new Color(-2310814));
        textPane1.setForeground(new Color(-2310814));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(textPane1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setBackground(new Color(-16240818));
        Font panel2Font = this.$$$getFont$$$(null, -1, -1, panel2.getFont());
        if (panel2Font != null) panel2.setFont(panel2Font);
        panel2.setForeground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        titoloLabel = new JLabel();
        titoloLabel.setBackground(new Color(-14793370));
        Font titoloLabelFont = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 20, titoloLabel.getFont());
        if (titoloLabelFont != null) titoloLabel.setFont(titoloLabelFont);
        titoloLabel.setForeground(new Color(-1));
        titoloLabel.setText("Specialisti nella diagnosi al servizio della tua salute");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 120, 0, 0);
        panel2.add(titoloLabel, gbc);
        disegnoLabel = new JLabel();
        disegnoLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(30, 0, 30, 0);
        panel2.add(disegnoLabel, gbc);
        testoLabel = new JLabel();
        Font testoLabelFont = this.$$$getFont$$$("Arial Rounded MT Bold", Font.PLAIN, 14, testoLabel.getFont());
        if (testoLabelFont != null) testoLabel.setFont(testoLabelFont);
        testoLabel.setForeground(new Color(-1));
        testoLabel.setText("La tua salute in mani sicure");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(150, 30, 0, 0);
        panel2.add(testoLabel, gbc);
        final JTextPane textPane2 = new JTextPane();
        textPane2.setBackground(new Color(-2310814));
        textPane2.setForeground(new Color(-2310814));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(textPane2, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
