package boundary;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;
import javax.swing.ImageIcon;
import java.net.URL;

public class PazienteForm {
    private JPanel contentPane;
    private JButton logoutButton;
    private JButton prenotaVisitaButton;
    private JButton leMieVisiteButton;
    private JLabel logoLabel;
    private JTextPane textPane1;
    private JLabel titoloLabel;
    private JLabel disegnoLabel;
    private JLabel testoLabel;
    private JPanel labelTitolo;


    private String nomeLoggato;
    private String cognomeLoggato;
    private String emailLoggato;
    private String recapitoTelefonicoLoggato;

    public PazienteForm(String nome, String cognome, String email, String recapitoTelefonico) {
        this.nomeLoggato = nome;
        this.cognomeLoggato = cognome;
        this.emailLoggato = email;
        this.recapitoTelefonicoLoggato = recapitoTelefonico;

        URL imgURL = getClass().getResource("/logo.png");
        URL imgURL1 = getClass().getResource("/disegno2.png");
        if (imgURL != null) {

            ImageIcon originalIcon = new ImageIcon(imgURL);


            Image scaledImage = originalIcon.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH);

            ImageIcon resizedIcon = new ImageIcon(scaledImage);
            logoLabel.setHorizontalAlignment(SwingConstants.CENTER);

            // 5. Rimuovi eventuale testo residuo e applica l'icona alla JLabel del Designer
            logoLabel.setText("");
            logoLabel.setIcon(resizedIcon);

        } else {
            System.err.println("Errore: Impossibile trovare il file del logo.");
        }
        if (imgURL1 != null) {

            ImageIcon originalIcon = new ImageIcon(imgURL1);


            Image scaledImage = originalIcon.getImage().getScaledInstance(480, -1, Image.SCALE_SMOOTH);

            ImageIcon resizedIcon = new ImageIcon(scaledImage);
            disegnoLabel.setHorizontalAlignment(SwingConstants.CENTER);

            // 5. Rimuovi eventuale testo residuo e applica l'icona alla JLabel del Designer
            disegnoLabel.setText("");
            disegnoLabel.setIcon(resizedIcon);

        } else {
            System.err.println("Errore: Impossibile trovare il file del logo.");
        }
        prenotaVisitaButton.addActionListener(e -> {
            // Chiude la finestra attuale in modo sicuro e dinamico
            Window win = SwingUtilities.getWindowAncestor(contentPane);
            if (win != null) {
                win.dispose();
            }
            SwingUtilities.invokeLater(() -> {
                new PrenotazioneForm(nomeLoggato, cognomeLoggato, emailLoggato, recapitoTelefonicoLoggato).apriPrenotazioneForm();
            });
        });

        logoutButton.addActionListener(e -> {
            // Chiude la finestra attuale in modo sicuro e dinamico
            Window win = SwingUtilities.getWindowAncestor(contentPane);
            if (win != null) {
                win.dispose();
            }
            SwingUtilities.invokeLater(() -> {
                new LoginForm().apriLoginForm();
            });
        });

        leMieVisiteButton.addActionListener(e -> {
            // qui in futuro: apri la lista visite del paziente
        });
    }

    public JPanel getContentPane() {
        return contentPane;
    }

    public JFrame apriForm() {
        JFrame frame = new JFrame("Area Paziente");
        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setBackground(new Color(-14793370));
        Font contentPaneFont = this.$$$getFont$$$("Arial", Font.BOLD, 24, contentPane.getFont());
        if (contentPaneFont != null) contentPane.setFont(contentPaneFont);
        contentPane.setForeground(new Color(-14793370));
        contentPane.setPreferredSize(new Dimension(800, 600));
        prenotaVisitaButton = new JButton();
        prenotaVisitaButton.setBackground(new Color(-10828087));
        Font prenotaVisitaButtonFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, prenotaVisitaButton.getFont());
        if (prenotaVisitaButtonFont != null) prenotaVisitaButton.setFont(prenotaVisitaButtonFont);
        prenotaVisitaButton.setForeground(new Color(-1));
        prenotaVisitaButton.setText("Prenota visita");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(prenotaVisitaButton, gbc);
        leMieVisiteButton = new JButton();
        leMieVisiteButton.setBackground(new Color(-10828087));
        Font leMieVisiteButtonFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, leMieVisiteButton.getFont());
        if (leMieVisiteButtonFont != null) leMieVisiteButton.setFont(leMieVisiteButtonFont);
        leMieVisiteButton.setForeground(new Color(-1));
        leMieVisiteButton.setText("Le mie visite");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(leMieVisiteButton, gbc);
        logoutButton = new JButton();
        logoutButton.setBackground(new Color(-10828087));
        Font logoutButtonFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, logoutButton.getFont());
        if (logoutButtonFont != null) logoutButton.setFont(logoutButtonFont);
        logoutButton.setForeground(new Color(-1));
        logoutButton.setText("Logout");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(logoutButton, gbc);
        logoLabel = new JLabel();
        Font logoLabelFont = this.$$$getFont$$$("Arial", Font.BOLD, 24, logoLabel.getFont());
        if (logoLabelFont != null) logoLabel.setFont(logoLabelFont);
        logoLabel.setForeground(new Color(-16764058));
        logoLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 35, 0);
        contentPane.add(logoLabel, gbc);
        textPane1 = new JTextPane();
        textPane1.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(textPane1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-16240818));
        Font panel1Font = this.$$$getFont$$$(null, -1, -1, panel1.getFont());
        if (panel1Font != null) panel1.setFont(panel1Font);
        panel1.setForeground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel1, gbc);
        titoloLabel = new JLabel();
        titoloLabel.setBackground(new Color(-14793370));
        Font titoloLabelFont = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 20, titoloLabel.getFont());
        if (titoloLabelFont != null) titoloLabel.setFont(titoloLabelFont);
        titoloLabel.setForeground(new Color(-1));
        titoloLabel.setText("Specialisti nella diagnosi al servizio della tua salute");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 120, 0, 0);
        panel1.add(titoloLabel, gbc);
        disegnoLabel = new JLabel();
        disegnoLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(30, 0, 30, 0);
        panel1.add(disegnoLabel, gbc);
        testoLabel = new JLabel();
        Font testoLabelFont = this.$$$getFont$$$("Arial Rounded MT Bold", Font.PLAIN, 14, testoLabel.getFont());
        if (testoLabelFont != null) testoLabel.setFont(testoLabelFont);
        testoLabel.setForeground(new Color(-1));
        testoLabel.setText("La tua salute è al centro del nostro ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 0, 0);
        panel1.add(testoLabel, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("impegno quotidiano.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}