package boundary;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class prenotazioneForm {
    private JPanel contentPane;
    private JTextField textField1;
    private JTextField textField2;
    private JComboBox comboBox1;
    private JComboBox comboBox2;
    private JLabel labelNome;
    private JLabel labelCognome;
    private JLabel labelSpecializzazione;
    private JLabel labelTitolo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(5, 4, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-14793370));
        Font contentPaneFont = this.$$$getFont$$$(null, -1, -1, contentPane.getFont());
        if (contentPaneFont != null) contentPane.setFont(contentPaneFont);
        contentPane.setForeground(new Color(-14793370));
        contentPane.setInheritsPopupMenu(false);
        contentPane.setOpaque(true);
        contentPane.setPreferredSize(new Dimension(450, 350));
        contentPane.setVisible(true);
        labelTitolo = new JLabel();
        labelTitolo.setAutoscrolls(true);
        labelTitolo.setBackground(new Color(-1));
        Font labelTitoloFont = this.$$$getFont$$$("Arial Black", -1, 20, labelTitolo.getFont());
        if (labelTitoloFont != null) labelTitolo.setFont(labelTitoloFont);
        labelTitolo.setForeground(new Color(-1));
        labelTitolo.setOpaque(false);
        labelTitolo.setText("Prenota la tua visita");
        labelTitolo.setVisible(true);
        contentPane.add(labelTitolo, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNome = new JLabel();
        labelNome.setBackground(new Color(-1));
        Font labelNomeFont = this.$$$getFont$$$("Arial", -1, 16, labelNome.getFont());
        if (labelNomeFont != null) labelNome.setFont(labelNomeFont);
        labelNome.setForeground(new Color(-1));
        labelNome.setOpaque(false);
        labelNome.setText("Nome");
        contentPane.add(labelNome, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        textField1.setBackground(new Color(-1));
        textField1.setCaretColor(new Color(-14793370));
        textField1.setDisabledTextColor(new Color(-14793370));
        textField1.setForeground(new Color(-1));
        textField1.setSelectedTextColor(new Color(-14793370));
        contentPane.add(textField1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelCognome = new JLabel();
        labelCognome.setBackground(new Color(-1));
        Font labelCognomeFont = this.$$$getFont$$$("Arial", -1, 16, labelCognome.getFont());
        if (labelCognomeFont != null) labelCognome.setFont(labelCognomeFont);
        labelCognome.setText("Cognome");
        contentPane.add(labelCognome, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField2 = new JTextField();
        contentPane.add(textField2, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        comboBox1 = new JComboBox();
        comboBox1.setEnabled(true);
        comboBox1.setFocusable(true);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("");
        defaultComboBoxModel1.addElement("Allergologia");
        defaultComboBoxModel1.addElement("Cardiologia");
        defaultComboBoxModel1.addElement("Dermatologia");
        defaultComboBoxModel1.addElement("Endocrinologia");
        defaultComboBoxModel1.addElement("Gastroenterologia");
        defaultComboBoxModel1.addElement("Geriatria");
        defaultComboBoxModel1.addElement("Ginecologia e Ostetricia");
        defaultComboBoxModel1.addElement("Neurologia");
        defaultComboBoxModel1.addElement("Oculistica");
        defaultComboBoxModel1.addElement("Ortopedia");
        defaultComboBoxModel1.addElement("Pediatria");
        defaultComboBoxModel1.addElement("Pneumologia");
        comboBox1.setModel(defaultComboBoxModel1);
        comboBox1.setOpaque(true);
        comboBox1.setRequestFocusEnabled(true);
        contentPane.add(comboBox1, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelSpecializzazione = new JLabel();
        labelSpecializzazione.setText("Specializzazione");
        contentPane.add(labelSpecializzazione, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Medico");
        contentPane.add(label1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboBox2 = new JComboBox();
        contentPane.add(comboBox2, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
