package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import control.VisitaController;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.net.URL;
import java.util.Locale;
import java.util.Map;
import java.util.List;

import javax.swing.ImageIcon;
import java.net.URL;

public class VisitaMedicoForm {
    private JPanel contentPane;
    private JPanel JPanel1;
    private JScrollPane scorrimento;
    private JPanel PanelCentrale;
    private JLabel logoLabel;
    private Long idMedico;
    private JFrame previousFrame;
    private JFrame currentFrame;

    public VisitaMedicoForm(Long idMedico, JFrame previousFrame) {
        this.idMedico = idMedico;
        this.previousFrame = previousFrame;
        scorrimento.getVerticalScrollBar().setUnitIncrement(20);
        URL imgURL = getClass().getResource("/logo.png");
        if (imgURL != null) {
            ImageIcon originalIcon = new ImageIcon(imgURL);
            Image scaledImage = originalIcon.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(scaledImage);
            logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
            // 5. Rimuovi eventuale testo residuo e applica l'icona alla JLabel del Designer
            logoLabel.setText("");
            logoLabel.setIcon(resizedIcon);

        } else {
            System.err.println("Errore: Impossibile trovare il file del logo.");
        }

    }

    public JFrame apriForm() {

        JFrame frame = new JFrame("Le mie visite");

        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.setSize(900, 650);
        frame.setLocationRelativeTo(null);

        this.currentFrame = frame;

        caricaVisite();

        previousFrame.setVisible(false);

        frame.setVisible(true);

        return frame;
    }

    private void caricaVisite() {
        //svuota il pannello
        PanelCentrale.removeAll();
        //dice a swing di mettere le card una sotto l'altra
        PanelCentrale.setLayout(new BoxLayout(PanelCentrale, BoxLayout.Y_AXIS));
        VisitaController controller = new VisitaController();
        List<Long> ids = controller.getIdVisitePerMedico(idMedico);
        for (Long id : ids) {
            Map<String, Object> visita = controller.getDettaglioVisita(id);
            JPanel card = creaSchedaVisita(visita);
            PanelCentrale.add(card);
            //metto uno spazio tra una card e l'altra
            PanelCentrale.add(Box.createVerticalStrut(15));
        }

        if (ids.isEmpty()) {
            JLabel lbl = new JLabel("Nessuna visita prenotata");
            lbl.setForeground(Color.WHITE);
            lbl.setFont(new Font("Arial", Font.BOLD, 18));
            lbl.setAlignmentX(Component.CENTER_ALIGNMENT);
            PanelCentrale.add(lbl);
        }

        PanelCentrale.revalidate();
        PanelCentrale.repaint();
    }

    private JPanel creaSchedaVisita(Map<String, Object> visita) {

        JPanel card = new JPanel();

        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));

        card.setBackground(Color.WHITE);
        card.setAlignmentX(Component.CENTER_ALIGNMENT);
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

        card.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.LIGHT_GRAY),
                BorderFactory.createEmptyBorder(15, 20, 15, 20)
        ));

        JLabel paziente = new JLabel((String) visita.get("paziente"));
        paziente.setFont(new Font("Arial", Font.BOLD, 18));
        JLabel data = new JLabel(visita.get("data") + "   " + visita.get("orario"));
        data.setFont(new Font("Arial", Font.PLAIN, 14));
        JLabel stato = new JLabel("Stato: " + visita.get("stato"));
        stato.setForeground(new Color(33, 150, 243));
        stato.setFont(new Font("Arial", Font.BOLD, 13));
        card.add(paziente);
        card.add(Box.createVerticalStrut(8));
        card.add(data);
        card.add(Box.createVerticalStrut(5));
        card.add(stato);
        return card;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        JPanel1 = new JPanel();
        JPanel1.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        JPanel1.setBackground(new Color(-15906911));
        contentPane.add(JPanel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial", Font.BOLD, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-1));
        label1.setText("AREA RISERVATA MEDICO");
        JPanel1.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial", -1, 14, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-5329488));
        label2.setText("Visualizza tutte le visite prenotate");
        JPanel1.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Arial", Font.BOLD, 18, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-1));
        label3.setText("Le mie visite");
        JPanel1.add(label3, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scorrimento = new JScrollPane();
        JPanel1.add(scorrimento, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelCentrale = new JPanel();
        PanelCentrale.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelCentrale.setBackground(new Color(-15906911));
        scorrimento.setViewportView(PanelCentrale);
        final JLabel label4 = new JLabel();
        label4.setBackground(new Color(-1));
        label4.setForeground(new Color(-16764058));
        label4.setText("Filtra per");
        JPanel1.add(label4, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoLabel = new JLabel();
        logoLabel.setText("Label");
        contentPane.add(logoLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
