package boundary;

import entity.Medico;
import entity.Visita;
import control.VisitaController;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.List;
import java.util.Locale;

public class VisiteMedicoForm {
    private JPanel contentPane;
    private JScrollPane scorrimento;
    private JPanel PanelCentrale;

    private Medico medicoLoggato;
    private JFrame previousFrame;
    private JFrame currentFrame;

    public VisiteMedicoForm(Medico medico, JFrame previousFrame) {
        this.medicoLoggato = medico;
        this.previousFrame = previousFrame;

        scorrimento.getVerticalScrollBar().setUnitIncrement(20);
    }

    public JFrame apriForm() {
        JFrame frame = new JFrame("Le mie visite");
        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);

        this.currentFrame = frame;

        caricaVisite();

        previousFrame.setVisible(false);
        frame.setVisible(true);

        return frame;
    }

    private void caricaVisite() {
        VisitaController controller = new VisitaController();

        PanelCentrale.setLayout(new BoxLayout(PanelCentrale, BoxLayout.Y_AXIS));

        List<Visita> visite = controller.getVisitePerMedico(medicoLoggato.getId());

        if (!visite.isEmpty()) {
            for (Visita v : visite) {
                JPanel scheda = creaSchedaVisita(v);
                PanelCentrale.add(scheda);
                PanelCentrale.add(Box.createVerticalStrut(12));
            }
        } else {
            JLabel emptyLbl = new JLabel("Nessuna visita prenotata");
            emptyLbl.setFont(new Font("Arial", Font.ITALIC, 16));
            emptyLbl.setForeground(new Color(0x999999));
            emptyLbl.setAlignmentX(Component.CENTER_ALIGNMENT);
            PanelCentrale.add(emptyLbl);
        }
    }

    private JPanel creaSchedaVisita(Visita v) {
        JPanel scheda = new JPanel();
        scheda.setLayout(new BoxLayout(scheda, BoxLayout.Y_AXIS));
        scheda.setBackground(Color.WHITE);
        scheda.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(0xDDDDDD), 1, true),
                BorderFactory.createEmptyBorder(15, 20, 15, 20)
        ));
        scheda.setAlignmentX(Component.LEFT_ALIGNMENT);
        scheda.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));

        JLabel pazienteLbl = new JLabel(v.getPaziente().getNome() + " " + v.getPaziente().getCognome());
        pazienteLbl.setFont(new Font("Arial", Font.BOLD, 18));
        pazienteLbl.setForeground(new Color(-14793370));

        JLabel dataOrarioLbl = new JLabel(v.getFasciaOraria().getData() + "  •  " + v.getFasciaOraria().getOrario());
        dataOrarioLbl.setFont(new Font("Arial", Font.PLAIN, 14));
        dataOrarioLbl.setForeground(new Color(0x666666));

        scheda.add(pazienteLbl);
        scheda.add(Box.createVerticalStrut(4));
        scheda.add(dataOrarioLbl);

        return scheda;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial", Font.BOLD, 24, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-14793370));
        label1.setText("AREA RISERVATA MEDICO");
        contentPane.add(label1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial", Font.ITALIC, 16, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Le mie visite");
        contentPane.add(label2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scorrimento = new JScrollPane();
        Font scorrimentoFont = this.$$$getFont$$$("Arial", -1, 14, scorrimento.getFont());
        if (scorrimentoFont != null) scorrimento.setFont(scorrimentoFont);
        contentPane.add(scorrimento, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelCentrale = new JPanel();
        PanelCentrale.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scorrimento.setViewportView(PanelCentrale);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}